project:
  type: website
  output-dir: docs

website:
  title: "Gradient Descent into Madness"
  site-url: https://bclarkson-code.github.io
  description: "Building an LLM completely from scratch"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bclarkson-code
      - icon: linkedin 
        href: https://www.linkedin.com/in/benedict-clarkson-779b43154/
      - icon: rss
        href: index.xml
  google-analytics: "G-KG3BJCW6QN"
  comments:
    utterances:
      repo: bclarkson-code/bclarkson-code.github.io
      label: comment
      theme: github-dark
  favicon: www/logo.png
  margin-header: subscribe.html

format:
  html:
    theme: cyborg
    css: styles.css
    highlight-style: atom-one

execute:
  freeze: auto


